# Generated by Django 5.0.4 on 2024-04-13 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('que', models.CharField(max_length=500)),
                ('op1', models.CharField(max_length=500)),
                ('op2', models.CharField(max_length=500)),
                ('op3', models.CharField(max_length=500)),
                ('op4', models.CharField(max_length=500)),
                ('corr_ans', models.CharField(max_length=500)),
            ],
        ),
    ]
