# Generated by Django 5.0.4 on 2024-04-18 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0005_remove_question_mark'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='mark',
            field=models.IntegerField(default=0),
        ),
    ]
